import logging
from core.reward import (
    RewardFunction, 
    StabilityReward, 
    AdsorptionTuningReward, 
    UncertaintyReward,
    DeviationDiscoveryReward,
    FunctionalReward,
    CompositeReward,
    SegregationReward
)
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

# Global Safety Constants
HARD_MAX_BUDGET = 100

class ResearchGovernor:
    """
    The Research Governor Agent (Agent 1).
    
    Acting as the "Lab Manager," this agent enforces the high-level boundaries 
    and directives of a scientific campaign. It is responsible for translating 
    categorical goals into mathematical reward functions and ensuring that 
    computational resources are used within safe limits.
    
    Responsibilities:
    1. Instantiating the appropriate RewardFunction (the BO objective).
    2. Enforcing computational budget ceilings (e.g., maximum evaluations).
    3. Maintaining global system constraints (e.g., allowed facets or elements).
    """
    def __init__(self, config: Dict[str, Any]) -> None:
        """
        Initialize the governor with a campaign configuration.
        
        Args:
            config: A dictionary defining the objective, budget, and constraints.
        """
        self.config = config
        self.reward_function = self._initialize_reward()
        
        # Enforce Hard Budget Ceiling to prevent runaway computational costs
        # especially important when campaigns are generated by LLMs.
        requested_budget = config.get("budget", {}).get("max_evaluations", 20)
        if requested_budget > HARD_MAX_BUDGET:
            logger.warning(f"Requested budget {requested_budget} exceeds the safety ceiling. "
                           f"Capping at {HARD_MAX_BUDGET} evaluations.")
            self.max_evaluations = HARD_MAX_BUDGET
        else:
            self.max_evaluations = requested_budget
            
        self.current_evaluations = 0

    def _initialize_reward(self) -> RewardFunction:
        """
        Factory method to instantiate the correct RewardFunction based on the goal.
        """
        obj = self.config.get("objective", {})
        obj_type = obj.get("type", "stability")
        
        # Mapping categorical goals to formal mathematical objectives
        if obj_type == "stability":
            return StabilityReward()
        elif obj_type == "adsorption_tuning":
            target = obj.get("target_e_ads", 0.0)
            return AdsorptionTuningReward(target_e_ads=target)
        elif obj_type == "uncertainty_maximization":
            return UncertaintyReward()
        elif obj_type == "deviation_discovery":
            return DeviationDiscoveryReward()
        elif obj_type == "segregation":
            # Targeted at surface enrichment of specific elements (e.g., Sr segregation)
            species = obj.get("target_species", "Sr")
            return SegregationReward(target_species=species)
        elif obj_type == "functional":
            # Allows users to provide a custom mathematical expression for the reward
            expr = obj.get("expression", "0.0")
            return FunctionalReward(expression=expr)
        elif obj_type == "composite":
            # Supports multi-objective optimization via weighted sums
            components = obj.get("components", [])
            rewards_map: Dict[RewardFunction, float] = {}
            for comp in components:
                temp_gov = ResearchGovernor({"objective": comp})
                weight = comp.get("weight", 1.0)
                rewards_map[temp_gov.get_reward_function()] = weight
            return CompositeReward(rewards=rewards_map)
        else:
            raise ValueError(f"Unsupported objective type: {obj_type}")

    def get_reward_function(self) -> RewardFunction:
        """Returns the active reward function for the BO loop."""
        return self.reward_function

    def has_budget(self) -> bool:
        """Checks if the evaluation budget is still available."""
        return self.current_evaluations < self.max_evaluations

    def consume_budget(self) -> None:
        """Registers the completion of one evaluation/experiment."""
        self.current_evaluations += 1

    def get_constraints(self) -> Dict[str, Any]:
        """Returns the physical and chemical constraints of the material space."""
        return self.config.get("constraints", {})
