from typing import List, Tuple, Dict, Any, Optional
import numpy as np
from optimization.surrogate import SurrogateModel
from optimization.acquisition import (
    AcquisitionFunction, 
    ExpectedImprovement, 
    UpperConfidenceBound, 
    ThompsonSampling
)
from core.state import SurfaceState
from core.action import MutationAction, ActionType
from core.transition import TransitionEngine

class ActionProposer:
    """
    Component responsible for suggesting candidate mutation actions.
    
    This acts as the "idea generator." It scans the current state and enumerates 
    physically permissible mutations (e.g., adding a vacancy, changing coverage).
    It separates the logic of *proposing* an experiment from the logic of *selecting* it.
    This architecture natively supports LLM-driven heuristic proposals in the future.
    """
    def propose_actions(self, state: SurfaceState) -> List[MutationAction]:
        """
        Suggest mutation operators for the current state.
        This is where 'Expert Knowledge' or 'LLM Heuristics' are applied.
        """
        actions = []
        
        # 1. Heuristic: Vacancies for all elements in bulk
        for el in state.bulk_composition.keys():
            actions.append(MutationAction(
                action_type=ActionType.INTRODUCE_VACANCY,
                parameters={"site": el, "index": 0}
            ))
            
        # 2. Heuristic: Coverage modifications
        for new_cov in [0.25, 0.5, 0.75, 1.0]:
            if abs(new_cov - state.coverage) > 0.01:
                actions.append(MutationAction(
                    action_type=ActionType.MODIFY_COVERAGE,
                    parameters={"coverage": new_cov}
                ))
                
        # 3. Heuristic: Substitutions
        # (e.g., doping Mn with Sr if Mn is present)
        if "Mn" in state.bulk_composition:
            actions.append(MutationAction(
                action_type=ActionType.SUBSTITUTIONAL_DOPANT,
                parameters={"original_element": "Mn", "dopant": "Sr"}
            ))

        # 4. Heuristic: Swapping (Segregation)
        # If Sr and La are present, propose swapping them
        if "Sr" in state.bulk_composition and "La" in state.bulk_composition:
            actions.append(MutationAction(
                action_type=ActionType.SWAP_ATOMS,
                parameters={"element_a": "La", "element_b": "Sr", "direction": "surface_to_bulk"}
            ))
            actions.append(MutationAction(
                action_type=ActionType.SWAP_ATOMS,
                parameters={"element_a": "Sr", "element_b": "La", "direction": "surface_to_bulk"}
            ))
            
        return actions

class OptimizationStrategist:
    """
    Agent 2 — Optimization Strategist (The Senior Postdoc).
    
    This agent executes Bayesian Optimization (BO). It does not generate structures itself;
    instead, it manages the `SurrogateModel` to predict the performance of candidate states.
    
    Workflow:
    1. Asks the `ActionProposer` for possible mutations.
    2. Applies those mutations via the `TransitionEngine` to get candidate `SurfaceStates`.
    3. Scores each candidate using the `SurrogateModel` and an `AcquisitionFunction` 
       (balancing exploration vs. exploitation).
    4. Selects the single best action to execute physically.
    """
    def __init__(self, surrogate: SurrogateModel, config: Dict[str, Any], proposer: Optional[ActionProposer] = None):
        self.surrogate = surrogate
        self.config = config
        self.proposer = proposer or ActionProposer()
        self.transition_engine = TransitionEngine()

    def select_next_action(
        self, 
        current_state: SurfaceState, 
        best_f: float
    ) -> Tuple[MutationAction, SurfaceState]:
        """
        Generate candidates via proposer, evaluate via surrogate, and select best.
        """
        # 1. Propose mutation operators (High-level suggestions)
        actions = self.proposer.propose_actions(current_state)
        
        # 2. Generate candidate states via formal transition engine
        candidates = []
        for action in actions:
            next_state = self.transition_engine.apply(current_state, action)
            candidates.append((action, next_state))

        if not candidates:
            raise ValueError("No candidate actions generated by proposer.")

        # 3. Selection via Acquisition Function
        acq_type = self.config.get("acquisition_type", "EI")
        if acq_type == "EI":
            acq_func = ExpectedImprovement(best_observed_f=best_f)
        elif acq_type == "UCB":
            acq_func = UpperConfidenceBound(kappa=self.config.get("kappa", 2.576))
        elif acq_type == "TS":
            acq_func = ThompsonSampling()
        else:
            raise ValueError(f"Unknown acquisition type: {acq_type}")

        # Score candidates
        scores = []
        for action, state in candidates:
            score = acq_func.compute_score(state, self.surrogate)
            scores.append(score)
            
        best_idx = int(np.argmax(scores))
        return candidates[best_idx]

    def update_model(self, dataset: List[Dict[str, Any]]):
        """Refit the surrogate model with new data."""
        self.surrogate.update(dataset)
